#!bin/bash

echo -e "\033[31mERRO\033[0m"

echo -e "\033[31mERRO\e[0m"

echo -e "\e[4mTexto Sublinhado \e[0m"


echo -e "Cor \e[30mBlack\e[0m"~
echo -e "Cor \e[31mRed\e[0m"
echo -e "Cor \e[32mGreen\e[0m"
echo -e "Cor \e[33mYellow\e[0m"
echo -e "Cor \e[34mBlue\e[0m"
echo -e "Cor \e[35mMagenta\e[0m"
echo -e "Cor \e[36mCyan\e[0m"
echo -e "Cor \e[37mLight Gray\e[0m"
echo -e "Cor \e[90mDark Gray\e[0m"
echo -e "Cor \e[91mLight Red\e[0m"
echo -e "Cor \e[92mLight Green\e[0m"
echo -e "Cor \e[93mLight Yellow\e[0m"
echo -e "Cor \e[94mLight Blue\e[0m"
echo -e "Cor \e[95mLight Magenta\e[0m"
echo -e "Cor \e[96mLight Cyan\e[0m"
echo -e "Cor \e[97mWhite\e[0m"

#Cor do Texto Vem Primeiro doq A a cor do Background
#Dessa Forma  "echo -e "\(Cor)[TXT;BCK(texto)\e[0m"

echo -e "\e[31;42mCor De Texto Vermelha e Fundo Verde\e[0m"

# Formatação em Variavel

VERMELHO="\e[31m"
VERDE="\e[32m"
AZUL="\e[34m"
RESET="\e[0m"

echo -e "${VERMELHO}Vermelho${RESET}" 
echo -e "${VERDE}Verde${RESET}"
echo -e "${AZUL}Azul${RESET}"