#!bin/bash

while true;
do

    clear
    echo "Escolha uma opcao: a, b ou s"
    echo "     a: Opcao A "
    echo "     b: Opcao B "
    echo "     s: Sair "
    read -sn 1 opcao

    case $opcao in
        
        a) echo "Voce digitou a opcao 'a'" ;;
        
        b) echo "Voce digitou a opcao 'b'" ;;
        
        s) echo "Saindo..."
            break
            ;;
        *) echo "Opcao invalida";;
    
    esac

    read -sn 1 -p "Pressione uma tecla para continuar..."

done